-- Customer registry for the management area.

create table if not exists public.customers (
  id integer generated by default as identity primary key,
  nome text not null,
  document text not null default '',
  email text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  zip_code text not null default '',
  address text not null default '',
  city text not null default '',
  state text not null default '',
  notes text not null default '',
  status public.catalog_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_status_idx on public.customers(status);
create index if not exists customers_nome_idx on public.customers(nome);
create index if not exists customers_document_idx on public.customers(document);

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

alter table public.customers enable row level security;

drop policy if exists "Authenticated catalog admins can read customers" on public.customers;
create policy "Authenticated catalog admins can read customers"
on public.customers for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can create customers" on public.customers;
create policy "Authenticated catalog admins can create customers"
on public.customers for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can update customers" on public.customers;
create policy "Authenticated catalog admins can update customers"
on public.customers for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());
