-- Independent rental quotes. Quotes can be generated before a contract exists.

create sequence if not exists public.rental_quote_number_seq
  as integer
  start with 1
  increment by 1
  minvalue 1;

create or replace function public.next_rental_quote_number()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'ORC-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.rental_quote_number_seq')::text, 4, '0');
$$;

create table if not exists public.rental_quotes (
  id integer generated by default as identity primary key,
  quote_number text not null default public.next_rental_quote_number(),
  customer_id integer references public.customers(id) on update cascade,
  customer_name text not null default '',
  customer_document text not null default '',
  customer_email text not null default '',
  customer_phone text not null default '',
  customer_address text not null default '',
  customer_city text not null default '',
  customer_state text not null default '',
  seller_id integer references public.staff_users(id) on update cascade,
  seller_name text not null default '',
  seller_email text not null default '',
  seller_phone text not null default '',
  billing_period text not null default 'daily',
  start_date date not null default current_date,
  valid_until date,
  delivery_address text not null default '',
  worksite_address text not null default '',
  notes text not null default '',
  subtotal_cents integer not null default 0,
  shipping_cents integer not null default 0,
  total_cents integer not null default 0,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rental_quotes_quote_number_key unique (quote_number),
  constraint rental_quotes_billing_period_check check (billing_period in ('daily', 'weekly', 'fortnightly', 'monthly')),
  constraint rental_quotes_status_check check (status in ('draft', 'sent', 'approved', 'rejected', 'expired')),
  constraint rental_quotes_amounts_check check (subtotal_cents >= 0 and shipping_cents >= 0 and total_cents >= 0)
);

create table if not exists public.rental_quote_items (
  id integer generated by default as identity primary key,
  quote_id integer not null references public.rental_quotes(id) on delete cascade,
  equipment_id integer not null references public.equipments(id) on update cascade,
  equipment_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  billing_period text not null default 'daily' check (billing_period in ('daily', 'weekly', 'fortnightly', 'monthly')),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  total_price_cents integer not null default 0 check (total_price_cents >= 0),
  asset_value_cents integer not null default 0 check (asset_value_cents >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists rental_quotes_quote_number_idx on public.rental_quotes(quote_number);
create index if not exists rental_quotes_customer_id_idx on public.rental_quotes(customer_id);
create index if not exists rental_quotes_seller_id_idx on public.rental_quotes(seller_id);
create index if not exists rental_quotes_status_idx on public.rental_quotes(status);
create index if not exists rental_quote_items_quote_id_idx on public.rental_quote_items(quote_id);

drop trigger if exists rental_quotes_set_updated_at on public.rental_quotes;
create trigger rental_quotes_set_updated_at
before update on public.rental_quotes
for each row execute function public.set_updated_at();

alter table public.rental_quotes enable row level security;
alter table public.rental_quote_items enable row level security;

drop policy if exists "Catalog admins can read rental quotes" on public.rental_quotes;
create policy "Catalog admins can read rental quotes"
on public.rental_quotes for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Catalog admins can create rental quotes" on public.rental_quotes;
create policy "Catalog admins can create rental quotes"
on public.rental_quotes for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Catalog admins can update rental quotes" on public.rental_quotes;
create policy "Catalog admins can update rental quotes"
on public.rental_quotes for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Catalog admins can delete rental quotes" on public.rental_quotes;
create policy "Catalog admins can delete rental quotes"
on public.rental_quotes for delete
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Catalog admins can read rental quote items" on public.rental_quote_items;
create policy "Catalog admins can read rental quote items"
on public.rental_quote_items for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Catalog admins can create rental quote items" on public.rental_quote_items;
create policy "Catalog admins can create rental quote items"
on public.rental_quote_items for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Catalog admins can update rental quote items" on public.rental_quote_items;
create policy "Catalog admins can update rental quote items"
on public.rental_quote_items for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Catalog admins can delete rental quote items" on public.rental_quote_items;
create policy "Catalog admins can delete rental quote items"
on public.rental_quote_items for delete
to authenticated
using (public.is_catalog_admin());
