create table if not exists public.invoice_pix_charges (
  id integer generated by default as identity primary key,
  contract_id integer not null references public.rental_contracts(id) on delete cascade on update cascade,
  invoice_number text not null,
  txid text not null,
  brcode text not null,
  pix_key text not null,
  receiver_name text not null default '',
  receiver_city text not null default '',
  amount_cents integer not null default 0,
  due_date date not null,
  additional_info text not null default '',
  status text not null default 'pending',
  end_to_end_id text not null default '',
  paid_amount_cents integer not null default 0,
  paid_at timestamptz,
  payer_ispb text not null default '',
  payer_bank_name text not null default '',
  payer_name text not null default '',
  payer_document text not null default '',
  risk_score integer not null default 0,
  risk_band text not null default 'low',
  risk_verdict text not null default 'approved',
  risk_signals jsonb not null default '[]'::jsonb,
  risk_evidences jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'invoice_pix_charges_amount_cents_check'
      and conrelid = 'public.invoice_pix_charges'::regclass
  ) then
    alter table public.invoice_pix_charges
      add constraint invoice_pix_charges_amount_cents_check check (amount_cents >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'invoice_pix_charges_paid_amount_cents_check'
      and conrelid = 'public.invoice_pix_charges'::regclass
  ) then
    alter table public.invoice_pix_charges
      add constraint invoice_pix_charges_paid_amount_cents_check check (paid_amount_cents >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'invoice_pix_charges_risk_score_check'
      and conrelid = 'public.invoice_pix_charges'::regclass
  ) then
    alter table public.invoice_pix_charges
      add constraint invoice_pix_charges_risk_score_check check (risk_score >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'invoice_pix_charges_status_check'
      and conrelid = 'public.invoice_pix_charges'::regclass
  ) then
    alter table public.invoice_pix_charges
      add constraint invoice_pix_charges_status_check
        check (status in ('pending', 'paid', 'review', 'rejected', 'cancelled'));
  end if;
end $$;

create unique index if not exists invoice_pix_charges_txid_key
  on public.invoice_pix_charges(txid);

create unique index if not exists invoice_pix_charges_end_to_end_id_key
  on public.invoice_pix_charges(end_to_end_id)
  where end_to_end_id <> '';

create index if not exists invoice_pix_charges_contract_id_idx
  on public.invoice_pix_charges(contract_id);

create index if not exists invoice_pix_charges_status_idx
  on public.invoice_pix_charges(status);

create index if not exists invoice_pix_charges_due_date_idx
  on public.invoice_pix_charges(due_date);

drop trigger if exists invoice_pix_charges_set_updated_at on public.invoice_pix_charges;
create trigger invoice_pix_charges_set_updated_at
before update on public.invoice_pix_charges
for each row execute function public.set_updated_at();

alter table public.invoice_pix_charges enable row level security;

drop policy if exists "Authenticated catalog admins can read invoice pix charges"
  on public.invoice_pix_charges;
create policy "Authenticated catalog admins can read invoice pix charges"
on public.invoice_pix_charges for select
using (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can create invoice pix charges"
  on public.invoice_pix_charges;
create policy "Authenticated catalog admins can create invoice pix charges"
on public.invoice_pix_charges for insert
with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can update invoice pix charges"
  on public.invoice_pix_charges;
create policy "Authenticated catalog admins can update invoice pix charges"
on public.invoice_pix_charges for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
