-- Catalog schema and initial data for Mega Equipamentos.
-- Generated from src/app/data on 2026-05-20T20:35:24.635Z.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'catalog_status') then
    create type public.catalog_status as enum ('active', 'archived');
  end if;
end
$$;

create table if not exists public.categories (
  id integer primary key,
  nome text not null,
  slug text not null unique,
  name text not null default '',
  icone text not null default '',
  avatar text not null default '',
  avatar_hero text,
  avatar_card text,
  video text,
  objetivo text not null default '',
  status public.catalog_status not null default 'active',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  category_id integer not null references public.categories(id) on update cascade,
  nome text not null,
  slug text not null unique,
  avatar text,
  video text,
  descricao text not null default '',
  aplicacao text not null default '',
  tipo_de_servico text not null default '',
  periodo_de_locacao text not null default '',
  diferenciais text not null default '',
  status public.catalog_status not null default 'active',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_prices (
  product_id integer primary key references public.products(id) on delete cascade,
  daily_price_cents integer not null default 0 check (daily_price_cents >= 0),
  weekly_price_cents integer not null default 0 check (weekly_price_cents >= 0),
  fortnightly_price_cents integer not null default 0 check (fortnightly_price_cents >= 0),
  monthly_price_cents integer not null default 0 check (monthly_price_cents >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_status_idx on public.products(status);
create index if not exists categories_status_idx on public.categories(status);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists product_prices_set_updated_at on public.product_prices;
create trigger product_prices_set_updated_at
before update on public.product_prices
for each row execute function public.set_updated_at();

insert into public.categories (id, nome, slug, name, icone, avatar, avatar_hero, avatar_card, video, objetivo, status, sort_order) values
  (1, 'Acesso e Elevação', 'acesso-e-elevacao', 'Access and Elevation', 'icones/Acesso_e_Elevacao.png', '/imagens/categorias/acesso-e-elevacao/hero.webp', '/imagens/categorias/acesso-e-elevacao/hero.webp', '/imagens/categorias/acesso-e-elevacao/card.webp', null, 'Facilitar o acesso e o transporte vertical de materiais e profissionais em diferentes níveis de obra, com equipamentos seguros e de alta performance.', 'active', 1),
  (2, 'Andaimes', 'andaimes', 'Scaffolding', 'icones/Andaime.png', '/imagens/categorias/andaimes/hero.webp', '/imagens/categorias/andaimes/hero.webp', '/imagens/categorias/andaimes/card.webp', null, 'Oferecer sistemas de andaimes modulares, seguros e de fácil montagem para serviços em altura.', 'active', 2),
  (3, 'Escoramento de Estruturas', 'escoramento-de-estruturas', 'Structural Shoring', 'icones/Escoramento_de_Estruturas.png', '/imagens/categorias/escoramento-de-estruturas/hero.webp', '/imagens/categorias/escoramento-de-estruturas/hero.webp', '/imagens/categorias/escoramento-de-estruturas/card.webp', 'videos/escoramento-de-estruturas.mp4', 'Sustentação temporária de lajes, vigas e pilares durante concretagens.', 'active', 3),
  (4, 'Compactação e Solo', 'compactacao-e-solo', 'Soil Compaction', 'icones/Compactacao_e_Solo.png', '/imagens/categorias/compactacao-e-solo/hero.webp', '/imagens/categorias/compactacao-e-solo/hero.webp', '/imagens/categorias/compactacao-e-solo/card.webp', null, 'Garantir estabilidade e resistência do solo antes da concretagem e pavimentação.', 'active', 4),
  (5, 'Concretagem', 'concretagem', 'Concreting', 'icones/Concretagem.png', '/imagens/categorias/concretagem/hero.webp', '/imagens/categorias/concretagem/hero.webp', '/imagens/categorias/concretagem/card.webp', null, 'Mistura e adensamento do concreto com eficiência e qualidade.', 'active', 5),
  (6, 'Corte e Demolição', 'corte-e-demolicao', 'Cutting and Demolition', 'icones/Corte_e_Demolicao.png', '/imagens/categorias/corte-e-demolicao/hero.webp', '/imagens/categorias/corte-e-demolicao/hero.webp', '/imagens/categorias/corte-e-demolicao/card.webp', null, 'Fornecer marteletes de diversos portes para demolições leves a pesadas de concretos e alvenarias.', 'active', 6),
  (7, 'Ferramentas Elétricas', 'ferramentas-eletricas', 'Power Tools', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNTYiIGhlaWdodD0iMjU2IiB2aWV3Qm94PSIwIDAgMjQgMjQiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0ZGRDIwMCIgc3Ryb2tlLXdpZHRoPSIxIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWRyaWxsLWljb24gbHVjaWRlLWRyaWxsIj48cGF0aCBkPSJNMTAgMThhMSAxIDAgMCAxIDEgMXYyYTEgMSAwIDAgMS0xIDFINWEzIDMgMCAwIDEtMy0zIDEgMSAwIDAgMSAxLTF6Ii8+PHBhdGggZD0iTTEzIDEwSDRhMiAyIDAgMCAxLTItMlY0YTIgMiAwIDAgMSAyLTJoOWExIDEgMCAwIDEgMSAxdjZhMSAxIDAgMCAxLTEgMWwtLjgxIDMuMjQyYTEgMSAwIDAgMS0uOTcuNzU4SDgiLz48cGF0aCBkPSJNMTQgNGgzYTEgMSAwIDAgMSAxIDF2MmExIDEgMCAwIDEtMSAxaC0zIi8+PHBhdGggZD0iTTE4IDZoNCIvPjxwYXRoIGQ9Im01IDEwLTIgOCIvPjxwYXRoIGQ9Im03IDE4IDItOCIvPjwvc3ZnPg==', '/imagens/categorias/ferramentas-eletricas/hero.webp', '/imagens/categorias/ferramentas-eletricas/hero.webp', '/imagens/categorias/ferramentas-eletricas/card.webp', null, 'Equipamentos de precisão e acabamento para marcenaria, instalação e manutenção.', 'active', 7),
  (8, 'Motores e Geradores', 'motores-e-geradores', 'Engines and Generators', 'icones/Motores_e_Geradores.png', '/imagens/categorias/motores-e-geradores/hero.webp', '/imagens/categorias/motores-e-geradores/hero.webp', '/imagens/categorias/motores-e-geradores/card.webp', null, 'Energia, compressão e bombeamento para obras e serviços gerais.', 'active', 8),
  (9, 'Reboque e Transporte', 'reboque-e-transporte', 'Trailers and Transport', 'icones/Reboque.png', '/imagens/categorias/reboque-e-transporte/hero.webp', '/imagens/categorias/reboque-e-transporte/hero.webp', '/imagens/categorias/reboque-e-transporte/card.webp', null, 'Soluções logísticas seguras para transporte de materiais e equipamentos.', 'active', 9),
  (10, 'Diversos', 'diversos', 'Miscellaneous', 'icones/Diversos.png', '/imagens/categorias/diversos/hero.webp', '/imagens/categorias/diversos/hero.webp', '/imagens/categorias/diversos/card.webp', null, 'Apoio à estrutura e organização do canteiro de obras.', 'active', 10)
on conflict (id) do update set
  nome = excluded.nome,
  slug = excluded.slug,
  name = excluded.name,
  icone = excluded.icone,
  avatar = excluded.avatar,
  avatar_hero = excluded.avatar_hero,
  avatar_card = excluded.avatar_card,
  video = excluded.video,
  objetivo = excluded.objetivo,
  sort_order = excluded.sort_order;

insert into public.products (id, category_id, nome, slug, avatar, video, descricao, aplicacao, tipo_de_servico, periodo_de_locacao, diferenciais, status, sort_order) values
  (1, 1, 'Guincho de Coluna 400 kg', 'guincho-de-coluna-400-kg', '/imagens/equipamentos/catalogo/acesso-e-elevacao/guincho-de-coluna-400-kg.webp', null, 'Guincho elétrico de coluna para içamento vertical de materiais até 400 kg. Leve, resistente e de fácil montagem em lajes e estruturas.', 'Construção civil, reformas, estruturas metálicas.', 'Içamento de materiais, alvenaria, concretagem.', 'Diária, Semanal, Quinzenal e Mensal.', 'Instalação rápida • Baixo consumo • Operação segura', 'active', 1),
  (2, 1, 'Escada de Extensão', 'escada-de-extensao', '/imagens/equipamentos/catalogo/acesso-e-elevacao/escada-de-extensao.webp', null, 'Escada telescópica de alumínio para acesso em altura, com travas de segurança e pés antiderrapantes.', 'Pintura, elétrica, manutenção predial, instalações em fachada.', 'Acesso e mobilidade vertical.', 'Diária, Semanal, Quinzenal e Mensal.', 'Leve e durável • Altura ajustável • Transporte fácil', 'active', 2),
  (3, 1, 'Talha Manual 1T', 'talha-manual-1t', '/imagens/equipamentos/catalogo/acesso-e-elevacao/talha-manual-1t.webp', null, 'Talha de corrente com capacidade de 1 tonelada para elevação precisa de cargas.', 'Serralheria, estruturas metálicas, montagens industriais.', 'Elevação e posicionamento de cargas.', 'Diária, Semanal, Quinzenal e Mensal.', 'Robustez • Baixa manutenção • Operação simples', 'active', 3),
  (4, 2, 'Painel de Andaime 1,00 × 1,50 m', 'painel-de-andaime-1-00-x-1-50-m', '/imagens/equipamentos/catalogo/andaimes/painel-de-andaime-1-00-x-1-50-m.webp', null, 'Painel tubular em aço para montagem de torres e fachadas; pintura protetiva e encaixe rápido.', 'Fachadas, pintura, reboco, manutenção.', 'Acesso e plataformas de trabalho.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta resistência • Padrão Mega • Montagem ágil', 'active', 4),
  (5, 2, 'Painel de Andaime 1,00 × 1,00 m', 'painel-de-andaime-1-00-x-1-00-m', '/imagens/equipamentos/catalogo/andaimes/painel-de-andaime-1-00-x-1-00-m.webp', null, 'Painel modular compacto para áreas com restrição de espaço/altura, compatível com toda a linha.', 'Obras internas, corredores, fachadas menores.', 'Acesso em espaços reduzidos.', 'Diária, Semanal, Quinzenal e Mensal.', 'Versátil • Leve • Compatível com plataformas e barras', 'active', 5),
  (6, 2, 'Plataforma Metálica', 'plataforma-metalica', '/imagens/equipamentos/catalogo/andaimes/plataforma-metalica.webp', null, 'Piso metálico antiderrapante para circulação segura nas torres de andaime.', 'Serviços em altura, pintura, acabamento.', 'Apoio e circulação.', 'Diária, Semanal, Quinzenal e Mensal.', 'Antiderrapante • Encaixe firme • Alta durabilidade', 'active', 6),
  (7, 2, 'Barra Diagonal', 'barra-diagonal', '/imagens/equipamentos/catalogo/andaimes/barra-diagonal.webp', null, 'Travamento estrutural para garantir rigidez e segurança das torres.', 'Torres e fachadas de andaime.', 'Reforço estrutural.', 'Diária, Semanal, Quinzenal e Mensal.', 'Galvanizada • Instalação rápida • Estabilidade', 'active', 7),
  (8, 2, 'Sapata Fixa', 'sapata-fixa', '/imagens/equipamentos/catalogo/andaimes/sapata-fixa.webp', null, 'Base de apoio para pisos nivelados, garantindo estabilidade do conjunto.', 'Pisos regulares e ambientes internos.', 'Apoio e sustentação.', 'Diária, Semanal, Quinzenal e Mensal.', 'Apoio firme • Proteção anticorrosiva • Compatibilidade total', 'active', 8),
  (9, 2, 'Sapata Ajustável', 'sapata-ajustavel', '/imagens/equipamentos/catalogo/andaimes/sapata-ajustavel.webp', null, 'Base com rosca para nivelamento em pisos irregulares.', 'Externas e terrenos desnivelados.', 'Apoio nivelador.', 'Diária, Semanal, Quinzenal e Mensal.', 'Ajuste preciso • Rosca reforçada • Produção própria', 'active', 9),
  (10, 2, 'Guarda-Corpo (com/sem porta)', 'guarda-corpo-com-sem-porta', '/imagens/equipamentos/catalogo/andaimes/guarda-corpo-com-sem-porta.webp', null, 'Proteção lateral para plataformas; opção com porta de acesso.', 'Fachadas e serviços verticais.', 'Proteção coletiva NR-18.', 'Diária, Semanal, Quinzenal e Mensal.', 'Travamento reforçado • Instalação fácil • Segurança', 'active', 10),
  (11, 2, 'Rodízio para Andaime', 'rodizio-para-andaime', '/imagens/equipamentos/catalogo/andaimes/rodizio-para-andaime.webp', null, 'Roda com trava dupla acoplada à base para movimentação segura.', 'Obras internas, manutenção e pintura.', 'Mobilidade de torres.', 'Diária, Semanal, Quinzenal e Mensal.', 'Rodas reforçadas • Travamento eficiente • Para pisos lisos', 'active', 11),
  (12, 2, 'Escada de Andaime', 'escada-de-andaime', '/imagens/equipamentos/catalogo/andaimes/escada-de-andaime.webp', null, 'Módulo de acesso com degraus antiderrapantes; opção com alçapão para passagem entre níveis.', 'Montagens de fachada, manutenção e pintura.', 'Acesso entre plataformas.', 'Diária, Semanal, Quinzenal e Mensal.', 'Compatível 1,00×1,50 e 1,00×1,00 • Alto grip • Estrutura robusta', 'active', 12),
  (13, 3, 'Escora Metálica 3,20 m', 'escora-metalica-3-20-m', '/imagens/equipamentos/catalogo/escoramento-de-estruturas/escora-metalica-3-20-m.webp', null, 'Escora regulável até 3,20 m, com rosca de ajuste e trava de segurança, para lajes e vigas de pequeno/médio porte.', 'Concretagem e reformas estruturais.', 'Escoramento temporário.', 'Diária, Semanal, Quinzenal e Mensal.', 'Ajuste preciso • Alta capacidade • Produção própria', 'active', 13),
  (14, 3, 'Escora Metálica 4,50 m', 'escora-metalica-4-50-m', '/imagens/equipamentos/catalogo/escoramento-de-estruturas/escora-metalica-4-50-m.webp', null, 'Escora regulável para grandes alturas (até 4,50 m) com reforço estrutural.', 'Galpões, mezaninos, edifícios com pé-direito alto.', 'Escoramento em grande altura.', 'Diária, Semanal, Quinzenal e Mensal.', 'Estrutura reforçada • Ampla regulagem • Pintura protetiva', 'active', 14),
  (15, 3, 'Forcado Simples/Duplo', 'forcado-simples-duplo', '/imagens/equipamentos/catalogo/escoramento-de-estruturas/forcado-simples-duplo.webp', null, 'Apoio superior para escoras, garantindo encaixe seguro de vigas.', 'Lajes, formas e vigas metálicas.', 'Apoio e sustentação de formas.', 'Diária, Semanal, Quinzenal e Mensal.', 'Encaixe rápido • Aço de alta resistência • Compatível com toda a linha', 'active', 15),
  (16, 3, 'Vigas Metálicas 1,3 m / 2 m / 3 m', 'vigas-metalicas-1-3-m-2-m-3-m', '/imagens/equipamentos/catalogo/escoramento-de-estruturas/vigas-metalicas-1-3-m-2-m-3-m.webp', null, 'Vigas de apoio para formas e lajes, em comprimentos variados.', 'Concretagem e estruturas temporárias.', 'Apoio estrutural e travamento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rigidez • Acabamento protetivo • Modularidade', 'active', 16),
  (17, 3, 'Barra de Ancoragem e Travamento', 'barra-de-ancoragem-e-travamento', '/imagens/equipamentos/catalogo/escoramento-de-estruturas/barra-de-ancoragem-e-travamento.webp', null, 'Sistema de barras/porcas para fixação e travamento de formas em vigas e pilares.', 'Concreto armado, pilares e painéis de forma.', 'Travamento e fixação estrutural.', 'Diária, Semanal, Quinzenal e Mensal.', 'Resistência à pressão • Alinhamento preciso • Montagem rápida', 'active', 17),
  (18, 4, 'Compactador de Solo (Sapo)', 'compactador-de-solo-sapo', '/imagens/equipamentos/catalogo/compactacao-e-solo/compactador-de-solo-sapo.webp', 'videos/compactador-de-solo-sapo.mp4', 'Compactador de percussão para valas, fundações e áreas confinadas; motor de alto rendimento.', 'Solo argiloso, bases de calçadas e fundações.', 'Preparação e nivelamento de solo.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta densidade • Robusto • Ideal para áreas de difícil acesso', 'active', 18),
  (19, 4, 'Placa Vibratória', 'placa-vibratoria', '/imagens/equipamentos/catalogo/compactacao-e-solo/placa-vibratoria.webp', null, 'Compactação de solos granulares, areia e brita, com acabamento uniforme.', 'Bases de pisos, calçadas, lajes e pavers.', 'Acabamento e nivelamento de superfícies.', 'Diária, Semanal, Quinzenal e Mensal.', 'Compactação homogênea • Operação simples • Baixo consumo', 'active', 19),
  (20, 5, 'Betoneira (200–400 L)', 'betoneira-200-400-l', '/imagens/equipamentos/catalogo/concretagem/betoneira-200-400-l.webp', null, 'Betoneira de mistura de concreto, argamassa e reboco; tambor basculante resistente e motor potente.', 'Obras de pequeno a grande porte.', 'Mistura e adensamento do concreto.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta capacidade • Robusto • Produção rápida', 'active', 20),
  (21, 5, 'Vibrador de Concreto', 'vibrador-de-concreto', '/imagens/equipamentos/catalogo/concretagem/vibrador-de-concreto.webp', null, 'Vibrador de concreto para adensamento do concreto recém-lançado, eliminando bolhas de ar e aumentando a resistência.', 'Lajes, pilares, vigas, sapatas.', 'Adensamento e estruturação de fundações.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta eficiência • Reduz falhas • Modelos elétrico/combustão', 'active', 21),
  (26, 6, 'Máquina de Cortar Piso', 'maquina-de-cortar-piso', '/imagens/equipamentos/catalogo/corte-e-demolicao/maquina-de-cortar-piso.webp', null, 'Corte linear em concreto/asfalto com disco diamantado.', 'Obras civis e serralheria.', 'Corte, desbaste e polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Corte limpo • Alta rotação • Fácil de operar', 'active', 22),
  (22, 6, 'Martelete Demolidor 30 kg', 'martelete-demolidor-30-kg', '/imagens/equipamentos/catalogo/corte-e-demolicao/martelete-demolidor-30-kg.webp', null, 'Martelete de alto impacto para demolições pesadas de concreto e pavimentos.', 'Fundações, blocos e pisos industriais.', 'Demolição pesada.', 'Diária, Semanal, Quinzenal e Mensal.', 'Potência elevada • Punhos antivibração • Alta confiabilidade', 'active', 23),
  (29, 6, 'Martelete 16 kg', 'martelete-16-kg', '/imagens/equipamentos/catalogo/corte-e-demolicao/martelete-16-kg.webp', null, 'Potente e resistente para concreto espesso e fundações.', 'Lajes espessas e bases de concreto.', 'Demolição estrutural.', 'Diária, Semanal, Quinzenal e Mensal.', 'Durabilidade • Alta força • Desempenho superior', 'active', 24),
  (28, 6, 'Martelete 11 kg', 'martelete-11-kg', '/imagens/equipamentos/catalogo/corte-e-demolicao/martelete-11-kg.webp', null, 'Alto poder de impacto para demolições médias/pesadas em concreto.', 'Fundações, blocos e pisos industriais.', 'Demolição pesada.', 'Diária, Semanal, Quinzenal e Mensal.', 'Potência equilibrada • Ergonômico • Confiável', 'active', 25),
  (23, 6, 'Martelete 6 kg', 'martelete-6-kg', '/imagens/equipamentos/catalogo/corte-e-demolicao/martelete-6-kg.webp', null, 'Martelete para perfurações e demolições leves/médias; leve e versátil.', 'Paredes, pisos e revestimentos.', 'Reforma e perfuração.', 'Diária, Semanal, Quinzenal e Mensal.', 'Compacto • Precisão • Menor fadiga do operador', 'active', 26),
  (27, 6, 'Martelete 2,5 kg', 'martelete-2-5-kg', '/imagens/equipamentos/catalogo/corte-e-demolicao/martelete-2-5-kg.webp', null, 'Leve e versátil para pequenos serviços e perfurações em alvenaria.', 'Reparos e demolições leves.', 'Reforma e acabamento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Leveza • Precisão • Fácil operação', 'active', 27),
  (24, 7, 'Serra Mármore', 'serra-marme', '/imagens/equipamentos/catalogo/ferramentas-eletricas/serra-marme.webp', null, 'Corte, desbaste e acabamento em metal, concreto e pedra.', 'Obras civis e serralheria.', 'Corte, desbaste e polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Corte limpo • Alta rotação • Fácil de operar', 'active', 28),
  (25, 7, 'Esmerilhadeira', 'esmerilhadeira', '/imagens/equipamentos/catalogo/ferramentas-eletricas/esmerilhadeira.webp', null, 'Corte, desbaste e acabamento em metal, concreto e pedra.', 'Obras civis e serralheria.', 'Corte, desbaste e polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Corte limpo • Alta rotação • Fácil de operar', 'active', 29),
  (30, 7, 'Pistola Finca-Pinos', 'pistola-fincapinos', '/imagens/equipamentos/catalogo/ferramentas-eletricas/pistola-fincapinos.webp', null, 'Fixação rápida de pinos em concreto e aço com cartuchos de pólvora.', 'Instalações elétricas, hidráulicas e estruturas.', 'Montagem e fixação.', 'Diária, Semanal, Quinzenal e Mensal.', 'Produtividade • Fixação instantânea • Sistema antirrecúo', 'active', 30),
  (31, 7, 'Serra Circular', 'serra-circular', '/imagens/equipamentos/catalogo/ferramentas-eletricas/serra-circular.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 31),
  (32, 7, 'Policorte', 'policorte', '/imagens/equipamentos/catalogo/ferramentas-eletricas/policorte.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 32),
  (33, 7, 'Perfuratriz', 'perfuratriz', '/imagens/equipamentos/catalogo/ferramentas-eletricas/perfuratriz.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 33),
  (34, 7, 'Politriz', 'politriz', '/imagens/equipamentos/catalogo/ferramentas-eletricas/politriz.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 34),
  (35, 7, 'Nível a Laser', 'nivel-a-laser', '/imagens/equipamentos/catalogo/ferramentas-eletricas/nivel-a-laser.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 35),
  (36, 7, 'Lixadeira de Parede', 'lixadeira-de-parede', '/imagens/equipamentos/catalogo/ferramentas-eletricas/lixadeira-de-parede.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 36),
  (37, 7, 'Pistola de Pintura Elétrica', 'pistola-de-pintura-eletrica', '/imagens/equipamentos/catalogo/ferramentas-eletricas/pistola-de-pintura-eletrica.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 37),
  (38, 7, 'Scanner de Parede', 'scanner-de-parede', '/imagens/equipamentos/catalogo/ferramentas-eletricas/scanner-de-parede.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 38),
  (39, 7, 'Furadeira e Parafusadeira', 'furadeira-e-parafusadeira', '/imagens/equipamentos/catalogo/ferramentas-eletricas/furadeira-e-parafusadeira.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 39),
  (40, 7, 'Plaina Elétrica', 'plaina-eletrica', '/imagens/equipamentos/catalogo/ferramentas-eletricas/plaina-eletrica.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 40),
  (41, 7, 'Soprador Térmico', 'soprador-thermal', '/imagens/equipamentos/catalogo/ferramentas-eletricas/soprador-thermal.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 41),
  (42, 8, 'Compressor de Ar 25 L', 'compressor-de-ar-25-l', '/imagens/equipamentos/catalogo/motores-e-geradores/compressor-de-ar-25-l.webp', null, 'Corte, desbaste e acabamento em metais, concreto e pedra.', 'Serralheria e obras civis.', 'Corte/desbaste/polimento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta rotação • Ergonomia • Trava de segurança', 'active', 42),
  (43, 8, 'Compressor de Ar 50 L', 'compressor-de-ar-50-l', '/imagens/equipamentos/catalogo/motores-e-geradores/compressor-de-ar-50-l.webp', null, 'Maior reservatório e pressão estável para uso contínuo em obras e serralherias.', 'Pistolas de pintura, ferramentas pneumáticas.', 'Pressurização e alimentação de ar.', 'Diária, Semanal, Quinzenal e Mensal.', 'Tanque reforçado • Válvula de segurança • Durável', 'active', 43),
  (48, 8, 'Gerador 5 kVA Monofásico', 'gerador-5-kva-monofasico', '/imagens/equipamentos/catalogo/motores-e-geradores/gerador-5-kva-monofasico.webp', null, 'Fornecimento de energia portátil para obras, eventos e emergências; baixo ruído.', 'Abastecimento temporário de equipamentos/iluminação.', 'Geração monofásica.', 'Diária, Semanal, Quinzenal e Mensal.', 'Energia estável • Autonomia prolongada • Operação simples', 'active', 44),
  (49, 8, 'Bomba Submersa de Água Suja (com Mangotes)', 'bomba-submersa-de-agua-suja-com-mangotes', '/imagens/equipamentos/catalogo/motores-e-geradores/bomba-submersa-de-agua-suja-com-mangotes.webp', null, 'Drenagem e esgotamento de água suja; desligamento automático por pressão.', 'Concretagem, obras civis e serviços gerais.', 'Drenagem e esgotamento.', 'Diária, Semanal, Quinzenal e Mensal.', 'Auto-limpeza • Baixo consumo • Baixo ruído', 'active', 45),
  (50, 8, 'Bomba Airless (Pintura)', 'bomba-airless-pintura', '/imagens/equipamentos/catalogo/motores-e-geradores/bomba-airless-pintura.webp', null, 'Pintura pressurizada sem ar, com alto rendimento e acabamento uniforme.', 'Paredes, estruturas metálicas e fachadas.', 'Pintura profissional.', 'Diária, Semanal, Quinzenal e Mensal.', 'Alta pressão • Baixo consumo • Baixo ruído', 'active', 46),
  (51, 9, 'Reboque 1,20 × 1,80 m (1 eixo)', 'reboque-1-20-x-1-80-m-1-eixo', '/imagens/equipamentos/catalogo/reboque-e-transporte/reboque-1-20-x-1-80-m-1-eixo.webp', null, 'Estrutura metálica reforçada para transporte leve; engate padrão e iluminação traseira.', 'Ferramentas, materiais e pequenos equipamentos.', 'Logística de pequeno porte.', 'Diária, Semanal, Quinzenal e Mensal.', 'Aço tubular • ~500 kg de carga • Ideal para utilitários', 'active', 47),
  (52, 9, 'Reboque 1,60 × 3,00 m (1 eixo)', 'reboque-1-60-x-3-00-m-1-eixo', '/imagens/equipamentos/catalogo/reboque-e-transporte/reboque-1-60-x-3-00-m-1-eixo.webp', null, 'Plataforma ampla para máquinas e materiais maiores; piso com chapa antiderrapante.', 'Betoneiras, compactadores e cargas médias.', 'Logística de médio porte.', 'Diária, Semanal, Quinzenal e Mensal.', 'Reforço estrutural • Até ~800 kg • Travamento seguro', 'active', 48),
  (53, 10, 'Banheiro de Obra (Módulo Sanitário)', 'banheiro-de-obra-modulo-sanitario', '/imagens/equipamentos/catalogo/diversos/banheiro-de-obra-modulo-sanitario.webp', null, 'Unidade sanitária móvel com ventilação e acabamento de fácil higienização.', 'Obras, eventos e áreas sem infraestrutura fixa.', 'Apoio de canteiro.', 'Diária, Semanal, Quinzenal e Mensal.', 'Leve • Instalação rápida • Atende NR-18', 'active', 49),
  (54, 10, 'Container Almoxarifado 1,50 × 3,00 × 2,00 m', 'container-almoxarifado-1-50-x-3-00-x-2-00-m', '/imagens/equipamentos/catalogo/diversos/container-almoxarifado-1-50-x-3-00-x-2-00-m.webp', null, 'Armazenamento seguro de ferramentas/insumos com porta e ventilação.', 'Logística e apoio em obras.', 'Guarda de materiais e suporte ao canteiro.', 'Diária, Semanal, Quinzenal e Mensal.', 'Estrutura soldada • Tranca de segurança • Piso reforçado', 'active', 50)
on conflict (id) do update set
  category_id = excluded.category_id,
  nome = excluded.nome,
  slug = excluded.slug,
  avatar = excluded.avatar,
  video = excluded.video,
  descricao = excluded.descricao,
  aplicacao = excluded.aplicacao,
  tipo_de_servico = excluded.tipo_de_servico,
  periodo_de_locacao = excluded.periodo_de_locacao,
  diferenciais = excluded.diferenciais,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select coalesce(max(id), 1) from public.products), 1));

insert into public.product_prices (product_id, daily_price_cents, weekly_price_cents, fortnightly_price_cents, monthly_price_cents, currency)
select id, 0, 0, 0, 0, 'BRL' from public.products
on conflict (product_id) do nothing;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_prices enable row level security;

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
on public.categories for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Authenticated can read all categories" on public.categories;
create policy "Authenticated can read all categories"
on public.categories for select
to authenticated
using (true);

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Authenticated can read all products" on public.products;
create policy "Authenticated can read all products"
on public.products for select
to authenticated
using (true);

drop policy if exists "Authenticated can create products" on public.products;
create policy "Authenticated can create products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update products" on public.products;
create policy "Authenticated can update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read prices for active products" on public.product_prices;
create policy "Public can read prices for active products"
on public.product_prices for select
to anon, authenticated
using (exists (select 1 from public.products p where p.id = product_prices.product_id and p.status = 'active'));

drop policy if exists "Authenticated can read all prices" on public.product_prices;
create policy "Authenticated can read all prices"
on public.product_prices for select
to authenticated
using (true);

drop policy if exists "Authenticated can create prices" on public.product_prices;
create policy "Authenticated can create prices"
on public.product_prices for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update prices" on public.product_prices;
create policy "Authenticated can update prices"
on public.product_prices for update
to authenticated
using (true)
with check (true);
