-- Seller registry and seller snapshots in rental contracts.

create table if not exists public.sellers (
  id integer generated by default as identity primary key,
  nome text not null,
  email text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  notes text not null default '',
  status public.catalog_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sellers_status_idx on public.sellers(status);
create index if not exists sellers_nome_idx on public.sellers(nome);

drop trigger if exists sellers_set_updated_at on public.sellers;
create trigger sellers_set_updated_at
before update on public.sellers
for each row execute function public.set_updated_at();

alter table public.sellers enable row level security;

drop policy if exists "Authenticated catalog admins can read sellers" on public.sellers;
create policy "Authenticated catalog admins can read sellers"
on public.sellers for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can create sellers" on public.sellers;
create policy "Authenticated catalog admins can create sellers"
on public.sellers for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can update sellers" on public.sellers;
create policy "Authenticated catalog admins can update sellers"
on public.sellers for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

alter table public.rental_contracts
  add column if not exists seller_id integer references public.sellers(id) on update cascade,
  add column if not exists seller_name text not null default '',
  add column if not exists seller_email text not null default '',
  add column if not exists seller_phone text not null default '';

create index if not exists rental_contracts_seller_id_idx on public.rental_contracts(seller_id);
