alter table public.financial_transactions
  add column if not exists expense_kind text;

update public.financial_transactions
set expense_kind = 'variable'
where type = 'expense'
  and expense_kind is null;

update public.financial_transactions
set expense_kind = null
where type = 'income';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'financial_transactions_expense_kind_check'
      and conrelid = 'public.financial_transactions'::regclass
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_expense_kind_check
      check (
        (type = 'expense' and expense_kind in ('fixed', 'variable'))
        or
        (type = 'income' and expense_kind is null)
      );
  end if;
end $$;

create table if not exists public.financial_transaction_categories (
  id integer generated by default as identity primary key,
  type text not null,
  name text not null,
  expense_kind text,
  status text not null default 'active',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists financial_transaction_categories_type_name_key
  on public.financial_transaction_categories(type, name);

create index if not exists financial_transaction_categories_type_idx
  on public.financial_transaction_categories(type);

create index if not exists financial_transaction_categories_status_idx
  on public.financial_transaction_categories(status);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'financial_transaction_categories_type_check'
      and conrelid = 'public.financial_transaction_categories'::regclass
  ) then
    alter table public.financial_transaction_categories
      add constraint financial_transaction_categories_type_check
      check (type in ('income', 'expense'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'financial_transaction_categories_status_check'
      and conrelid = 'public.financial_transaction_categories'::regclass
  ) then
    alter table public.financial_transaction_categories
      add constraint financial_transaction_categories_status_check
      check (status in ('active', 'archived'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'financial_transaction_categories_expense_kind_check'
      and conrelid = 'public.financial_transaction_categories'::regclass
  ) then
    alter table public.financial_transaction_categories
      add constraint financial_transaction_categories_expense_kind_check
      check (
        (type = 'expense' and expense_kind in ('fixed', 'variable'))
        or
        (type = 'income' and expense_kind is null)
      );
  end if;
end $$;

insert into public.financial_transaction_categories (type, name, expense_kind, sort_order)
select distinct
  ft.type,
  ft.category,
  case when ft.type = 'expense' then coalesce(ft.expense_kind, 'variable') else null end,
  0
from public.financial_transactions ft
where nullif(trim(ft.category), '') is not null
on conflict (type, name) do nothing;

drop trigger if exists financial_transaction_categories_set_updated_at
  on public.financial_transaction_categories;

create trigger financial_transaction_categories_set_updated_at
before update on public.financial_transaction_categories
for each row execute function public.set_updated_at();

alter table public.financial_transaction_categories enable row level security;

drop policy if exists "Authenticated catalog admins can read financial transaction categories"
  on public.financial_transaction_categories;
create policy "Authenticated catalog admins can read financial transaction categories"
on public.financial_transaction_categories for select
using (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can create financial transaction categories"
  on public.financial_transaction_categories;
create policy "Authenticated catalog admins can create financial transaction categories"
on public.financial_transaction_categories for insert
with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can update financial transaction categories"
  on public.financial_transaction_categories;
create policy "Authenticated catalog admins can update financial transaction categories"
on public.financial_transaction_categories for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can delete financial transaction categories"
  on public.financial_transaction_categories;
create policy "Authenticated catalog admins can delete financial transaction categories"
on public.financial_transaction_categories for delete
using (auth.role() = 'authenticated');
