-- Rental contracts with customer/equipment snapshots and PDF export source data.

create sequence if not exists public.rental_contract_number_seq;

create table if not exists public.rental_contracts (
  id integer generated by default as identity primary key,
  contract_number text not null unique default (
    'MEGA-' ||
    to_char(now(), 'YYYY') ||
    '-' ||
    lpad(nextval('public.rental_contract_number_seq')::text, 4, '0')
  ),
  customer_id integer not null references public.customers(id) on update cascade,
  customer_name text not null default '',
  customer_document text not null default '',
  customer_email text not null default '',
  customer_phone text not null default '',
  customer_address text not null default '',
  customer_city text not null default '',
  customer_state text not null default '',
  start_date date not null,
  end_date date,
  delivery_address text not null default '',
  notes text not null default '',
  terms text not null default '',
  subtotal_cents integer not null default 0 check (subtotal_cents >= 0),
  total_cents integer not null default 0 check (total_cents >= 0),
  status text not null default 'draft' check (status in ('draft', 'active', 'closed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rental_contract_items (
  id integer generated by default as identity primary key,
  contract_id integer not null references public.rental_contracts(id) on delete cascade,
  equipment_id integer not null references public.equipments(id) on update cascade,
  equipment_name text not null default '',
  quantity integer not null default 1 check (quantity > 0),
  billing_period text not null default 'daily' check (billing_period in ('daily', 'weekly', 'fortnightly', 'monthly')),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  total_price_cents integer not null default 0 check (total_price_cents >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists rental_contracts_customer_id_idx on public.rental_contracts(customer_id);
create index if not exists rental_contracts_status_idx on public.rental_contracts(status);
create index if not exists rental_contracts_start_date_idx on public.rental_contracts(start_date);
create index if not exists rental_contract_items_contract_id_idx on public.rental_contract_items(contract_id);
create index if not exists rental_contract_items_equipment_id_idx on public.rental_contract_items(equipment_id);

drop trigger if exists rental_contracts_set_updated_at on public.rental_contracts;
create trigger rental_contracts_set_updated_at
before update on public.rental_contracts
for each row execute function public.set_updated_at();

drop trigger if exists rental_contract_items_set_updated_at on public.rental_contract_items;
create trigger rental_contract_items_set_updated_at
before update on public.rental_contract_items
for each row execute function public.set_updated_at();

alter table public.rental_contracts enable row level security;
alter table public.rental_contract_items enable row level security;

drop policy if exists "Authenticated catalog admins can read rental contracts" on public.rental_contracts;
create policy "Authenticated catalog admins can read rental contracts"
on public.rental_contracts for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can create rental contracts" on public.rental_contracts;
create policy "Authenticated catalog admins can create rental contracts"
on public.rental_contracts for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can update rental contracts" on public.rental_contracts;
create policy "Authenticated catalog admins can update rental contracts"
on public.rental_contracts for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can read rental contract items" on public.rental_contract_items;
create policy "Authenticated catalog admins can read rental contract items"
on public.rental_contract_items for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can create rental contract items" on public.rental_contract_items;
create policy "Authenticated catalog admins can create rental contract items"
on public.rental_contract_items for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can update rental contract items" on public.rental_contract_items;
create policy "Authenticated catalog admins can update rental contract items"
on public.rental_contract_items for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Authenticated catalog admins can delete rental contract items" on public.rental_contract_items;
create policy "Authenticated catalog admins can delete rental contract items"
on public.rental_contract_items for delete
to authenticated
using (public.is_catalog_admin());
