create table if not exists public.financial_transactions (
  id integer generated by default as identity primary key,
  type text not null,
  source text not null default 'manual',
  description text not null,
  category text not null default '',
  amount_cents integer not null default 0,
  movement_date date not null,
  status text not null default 'confirmed',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'financial_transactions_type_check'
      and conrelid = 'public.financial_transactions'::regclass
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_type_check check (type in ('income', 'expense'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'financial_transactions_status_check'
      and conrelid = 'public.financial_transactions'::regclass
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_status_check check (status in ('pending', 'confirmed', 'cancelled'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'financial_transactions_amount_cents_check'
      and conrelid = 'public.financial_transactions'::regclass
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_amount_cents_check check (amount_cents >= 0);
  end if;
end $$;

create index if not exists financial_transactions_type_idx
  on public.financial_transactions(type);

create index if not exists financial_transactions_status_idx
  on public.financial_transactions(status);

create index if not exists financial_transactions_movement_date_idx
  on public.financial_transactions(movement_date);

drop trigger if exists financial_transactions_set_updated_at on public.financial_transactions;
create trigger financial_transactions_set_updated_at
before update on public.financial_transactions
for each row execute function public.set_updated_at();

alter table public.financial_transactions enable row level security;

drop policy if exists "Authenticated catalog admins can read financial transactions"
  on public.financial_transactions;
create policy "Authenticated catalog admins can read financial transactions"
on public.financial_transactions for select
using (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can create financial transactions"
  on public.financial_transactions;
create policy "Authenticated catalog admins can create financial transactions"
on public.financial_transactions for insert
with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated catalog admins can update financial transactions"
  on public.financial_transactions;
create policy "Authenticated catalog admins can update financial transactions"
on public.financial_transactions for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
