-- Lead registry and required lead link for rental quotes.

create table if not exists public.leads (
  id integer generated by default as identity primary key,
  nome text not null,
  document text not null default '',
  email text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  zip_code text not null default '',
  address text not null default '',
  city text not null default '',
  state text not null default '',
  origin text not null default 'whatsapp',
  interest_category_id integer references public.categories(id) on update cascade,
  interest_category_name text not null default '',
  notes text not null default '',
  customer_id integer references public.customers(id) on update cascade,
  status public.catalog_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leads_origin_check check (
    origin in (
      'indicacao',
      'google',
      'instagram',
      'facebook',
      'visita_comercial',
      'ligacao_comercial',
      'cliente',
      'loja',
      'whatsapp'
    )
  )
);

create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_nome_idx on public.leads(nome);
create index if not exists leads_origin_idx on public.leads(origin);
create index if not exists leads_interest_category_id_idx on public.leads(interest_category_id);
create index if not exists leads_customer_id_idx on public.leads(customer_id);

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

alter table public.leads enable row level security;

drop policy if exists "Catalog admins can read leads" on public.leads;
create policy "Catalog admins can read leads"
on public.leads for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Catalog admins can create leads" on public.leads;
create policy "Catalog admins can create leads"
on public.leads for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Catalog admins can update leads" on public.leads;
create policy "Catalog admins can update leads"
on public.leads for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

alter table public.rental_quotes
  add column if not exists lead_id integer references public.leads(id) on update cascade,
  add column if not exists lead_name text not null default '',
  add column if not exists lead_document text not null default '',
  add column if not exists lead_email text not null default '',
  add column if not exists lead_phone text not null default '',
  add column if not exists lead_address text not null default '',
  add column if not exists lead_city text not null default '',
  add column if not exists lead_state text not null default '',
  add column if not exists lead_origin text not null default 'cliente',
  add column if not exists lead_interest_category_id integer references public.categories(id) on update cascade,
  add column if not exists lead_interest_category_name text not null default '';

do $$
declare
  quote_row record;
  inserted_lead_id integer;
  lead_nome text;
begin
  for quote_row in
    select
      id,
      quote_number,
      customer_id,
      customer_name,
      customer_document,
      customer_email,
      customer_phone,
      customer_address,
      customer_city,
      customer_state,
      notes
    from public.rental_quotes
    where lead_id is null
    order by id
  loop
    lead_nome := coalesce(nullif(quote_row.customer_name, ''), 'Interessado ' || quote_row.quote_number);

    insert into public.leads (
      nome,
      document,
      email,
      phone,
      whatsapp,
      address,
      city,
      state,
      origin,
      notes,
      customer_id,
      status
    ) values (
      lead_nome,
      coalesce(quote_row.customer_document, ''),
      coalesce(quote_row.customer_email, ''),
      coalesce(quote_row.customer_phone, ''),
      coalesce(quote_row.customer_phone, ''),
      coalesce(quote_row.customer_address, ''),
      coalesce(quote_row.customer_city, ''),
      coalesce(quote_row.customer_state, ''),
      'cliente',
      trim(both from concat_ws(E'\n', nullif(quote_row.notes, ''), 'Criado automaticamente a partir do orcamento ' || quote_row.quote_number || '.')),
      quote_row.customer_id,
      'active'
    )
    returning id into inserted_lead_id;

    update public.rental_quotes
    set
      lead_id = inserted_lead_id,
      lead_name = lead_nome,
      lead_document = coalesce(quote_row.customer_document, ''),
      lead_email = coalesce(quote_row.customer_email, ''),
      lead_phone = coalesce(quote_row.customer_phone, ''),
      lead_address = coalesce(quote_row.customer_address, ''),
      lead_city = coalesce(quote_row.customer_city, ''),
      lead_state = coalesce(quote_row.customer_state, ''),
      lead_origin = 'cliente'
    where id = quote_row.id;
  end loop;
end $$;

update public.rental_quotes as rq
set
  lead_name = coalesce(nullif(rq.lead_name, ''), l.nome),
  lead_document = coalesce(nullif(rq.lead_document, ''), l.document),
  lead_email = coalesce(nullif(rq.lead_email, ''), l.email),
  lead_phone = coalesce(nullif(rq.lead_phone, ''), nullif(l.whatsapp, ''), l.phone),
  lead_address = coalesce(nullif(rq.lead_address, ''), l.address),
  lead_city = coalesce(nullif(rq.lead_city, ''), l.city),
  lead_state = coalesce(nullif(rq.lead_state, ''), l.state),
  lead_origin = coalesce(nullif(rq.lead_origin, ''), l.origin),
  lead_interest_category_id = coalesce(rq.lead_interest_category_id, l.interest_category_id),
  lead_interest_category_name = coalesce(nullif(rq.lead_interest_category_name, ''), l.interest_category_name)
from public.leads as l
where rq.lead_id = l.id;

alter table public.rental_quotes
  alter column lead_id set not null;

create index if not exists rental_quotes_lead_id_idx on public.rental_quotes(lead_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rental_quotes_lead_origin_check'
      and conrelid = 'public.rental_quotes'::regclass
  ) then
    alter table public.rental_quotes
      add constraint rental_quotes_lead_origin_check check (
        lead_origin in (
          'indicacao',
          'google',
          'instagram',
          'facebook',
          'visita_comercial',
          'ligacao_comercial',
          'cliente',
          'loja',
          'whatsapp'
        )
      );
  end if;
end $$;
