CREATE TYPE "public"."catalog_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY NOT NULL,
	"category_code" text DEFAULT '' NOT NULL,
	"nome" text NOT NULL,
	"slug" text NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"icone" text DEFAULT '' NOT NULL,
	"avatar" text DEFAULT '' NOT NULL,
	"avatar_hero" text,
	"avatar_card" text,
	"video" text,
	"objetivo" text DEFAULT '' NOT NULL,
	"status" "catalog_status" DEFAULT 'active' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company_profile" (
	"id" integer PRIMARY KEY NOT NULL,
	"legal_name" text NOT NULL,
	"trade_name" text DEFAULT '' NOT NULL,
	"document" text DEFAULT '' NOT NULL,
	"pix_key" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"gmail_password" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"whatsapp" text DEFAULT '' NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"city" text DEFAULT '' NOT NULL,
	"state" text DEFAULT '' NOT NULL,
	"zip_code" text DEFAULT '' NOT NULL,
	"instagram_login" text DEFAULT '' NOT NULL,
	"instagram_password" text DEFAULT '' NOT NULL,
	"contract_terms" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "company_profile_id_check" CHECK ("company_profile"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" text NOT NULL,
	"document" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"whatsapp" text DEFAULT '' NOT NULL,
	"zip_code" text DEFAULT '' NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"city" text DEFAULT '' NOT NULL,
	"state" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" "catalog_status" DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "equipment_prices" (
	"equipment_id" integer PRIMARY KEY NOT NULL,
	"daily_price_cents" integer DEFAULT 0 NOT NULL,
	"weekly_price_cents" integer DEFAULT 0 NOT NULL,
	"fortnightly_price_cents" integer DEFAULT 0 NOT NULL,
	"monthly_price_cents" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'BRL' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "equipment_prices_daily_price_cents_check" CHECK ("equipment_prices"."daily_price_cents" >= 0),
	CONSTRAINT "equipment_prices_weekly_price_cents_check" CHECK ("equipment_prices"."weekly_price_cents" >= 0),
	CONSTRAINT "equipment_prices_fortnightly_price_cents_check" CHECK ("equipment_prices"."fortnightly_price_cents" >= 0),
	CONSTRAINT "equipment_prices_monthly_price_cents_check" CHECK ("equipment_prices"."monthly_price_cents" >= 0),
	CONSTRAINT "equipment_prices_currency_check" CHECK ("equipment_prices"."currency" = 'BRL')
);
--> statement-breakpoint
CREATE TABLE "equipments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "equipments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_id" integer NOT NULL,
	"nome" text NOT NULL,
	"technical_name" text DEFAULT '' NOT NULL,
	"slug" text NOT NULL,
	"avatar" text,
	"video" text,
	"descricao" text DEFAULT '' NOT NULL,
	"aplicacao" text DEFAULT '' NOT NULL,
	"tipo_de_servico" text DEFAULT '' NOT NULL,
	"periodo_de_locacao" text DEFAULT '' NOT NULL,
	"diferenciais" text DEFAULT '' NOT NULL,
	"equipment_code" text DEFAULT '' NOT NULL,
	"asset_value_cents" integer DEFAULT 0 NOT NULL,
	"total_invested_cents" integer DEFAULT 0 NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"stock_quantity" integer DEFAULT 0 NOT NULL,
	"status" "catalog_status" DEFAULT 'active' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "equipments_asset_value_cents_check" CHECK ("equipments"."asset_value_cents" >= 0),
	CONSTRAINT "equipments_total_invested_cents_check" CHECK ("equipments"."total_invested_cents" >= 0),
	CONSTRAINT "equipments_stock_quantity_check" CHECK ("equipments"."stock_quantity" >= 0)
);
--> statement-breakpoint
CREATE TABLE "rental_contract_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rental_contract_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"equipment_id" integer NOT NULL,
	"equipment_name" text DEFAULT '' NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"billing_period" text DEFAULT 'daily' NOT NULL,
	"unit_price_cents" integer DEFAULT 0 NOT NULL,
	"total_price_cents" integer DEFAULT 0 NOT NULL,
	"asset_value_cents" integer DEFAULT 0 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rental_contract_items_quantity_check" CHECK ("rental_contract_items"."quantity" > 0),
	CONSTRAINT "rental_contract_items_billing_period_check" CHECK ("rental_contract_items"."billing_period" in ('daily', 'weekly', 'fortnightly', 'monthly')),
	CONSTRAINT "rental_contract_items_unit_price_cents_check" CHECK ("rental_contract_items"."unit_price_cents" >= 0),
	CONSTRAINT "rental_contract_items_total_price_cents_check" CHECK ("rental_contract_items"."total_price_cents" >= 0),
	CONSTRAINT "rental_contract_items_asset_value_cents_check" CHECK ("rental_contract_items"."asset_value_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE "rental_contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rental_contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_number" text DEFAULT public.format_rental_contract_number(nextval('public.rental_contract_number_seq')) NOT NULL,
	"previous_contract_number" text,
	"customer_id" integer NOT NULL,
	"customer_name" text DEFAULT '' NOT NULL,
	"customer_document" text DEFAULT '' NOT NULL,
	"customer_email" text DEFAULT '' NOT NULL,
	"customer_phone" text DEFAULT '' NOT NULL,
	"customer_address" text DEFAULT '' NOT NULL,
	"customer_city" text DEFAULT '' NOT NULL,
	"customer_state" text DEFAULT '' NOT NULL,
	"seller_id" integer,
	"seller_name" text DEFAULT '' NOT NULL,
	"seller_email" text DEFAULT '' NOT NULL,
	"seller_phone" text DEFAULT '' NOT NULL,
	"billing_period" text DEFAULT 'daily' NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date,
	"delivery_address" text DEFAULT '' NOT NULL,
	"worksite_address" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"terms" text DEFAULT '' NOT NULL,
	"subtotal_cents" integer DEFAULT 0 NOT NULL,
	"shipping_cents" integer DEFAULT 6000 NOT NULL,
	"total_cents" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rental_contracts_billing_period_check" CHECK ("rental_contracts"."billing_period" in ('daily', 'weekly', 'fortnightly', 'monthly')),
	CONSTRAINT "rental_contracts_status_check" CHECK ("rental_contracts"."status" in ('draft', 'active', 'closed', 'returned', 'cancelled')),
	CONSTRAINT "rental_contracts_subtotal_cents_check" CHECK ("rental_contracts"."subtotal_cents" >= 0),
	CONSTRAINT "rental_contracts_shipping_cents_check" CHECK ("rental_contracts"."shipping_cents" >= 0),
	CONSTRAINT "rental_contracts_total_cents_check" CHECK ("rental_contracts"."total_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE "rental_quote_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rental_quote_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quote_id" integer NOT NULL,
	"equipment_id" integer NOT NULL,
	"equipment_name" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"billing_period" text DEFAULT 'daily' NOT NULL,
	"unit_price_cents" integer DEFAULT 0 NOT NULL,
	"total_price_cents" integer DEFAULT 0 NOT NULL,
	"asset_value_cents" integer DEFAULT 0 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rental_quote_items_quantity_check" CHECK ("rental_quote_items"."quantity" > 0),
	CONSTRAINT "rental_quote_items_billing_period_check" CHECK ("rental_quote_items"."billing_period" in ('daily', 'weekly', 'fortnightly', 'monthly')),
	CONSTRAINT "rental_quote_items_unit_price_cents_check" CHECK ("rental_quote_items"."unit_price_cents" >= 0),
	CONSTRAINT "rental_quote_items_total_price_cents_check" CHECK ("rental_quote_items"."total_price_cents" >= 0),
	CONSTRAINT "rental_quote_items_asset_value_cents_check" CHECK ("rental_quote_items"."asset_value_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE "rental_quotes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rental_quotes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quote_number" text DEFAULT public.next_rental_quote_number() NOT NULL,
	"customer_id" integer,
	"customer_name" text DEFAULT '' NOT NULL,
	"customer_document" text DEFAULT '' NOT NULL,
	"customer_email" text DEFAULT '' NOT NULL,
	"customer_phone" text DEFAULT '' NOT NULL,
	"customer_address" text DEFAULT '' NOT NULL,
	"customer_city" text DEFAULT '' NOT NULL,
	"customer_state" text DEFAULT '' NOT NULL,
	"seller_id" integer,
	"seller_name" text DEFAULT '' NOT NULL,
	"seller_email" text DEFAULT '' NOT NULL,
	"seller_phone" text DEFAULT '' NOT NULL,
	"billing_period" text DEFAULT 'daily' NOT NULL,
	"start_date" date DEFAULT now() NOT NULL,
	"valid_until" date,
	"delivery_address" text DEFAULT '' NOT NULL,
	"worksite_address" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"subtotal_cents" integer DEFAULT 0 NOT NULL,
	"shipping_cents" integer DEFAULT 0 NOT NULL,
	"total_cents" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rental_quotes_billing_period_check" CHECK ("rental_quotes"."billing_period" in ('daily', 'weekly', 'fortnightly', 'monthly')),
	CONSTRAINT "rental_quotes_status_check" CHECK ("rental_quotes"."status" in ('draft', 'sent', 'approved', 'rejected', 'expired')),
	CONSTRAINT "rental_quotes_amounts_check" CHECK ("rental_quotes"."subtotal_cents" >= 0 and "rental_quotes"."shipping_cents" >= 0 and "rental_quotes"."total_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE "staff_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "staff_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"auth_user_id" uuid,
	"nome" text NOT NULL,
	"role" text DEFAULT 'vendedor' NOT NULL,
	"document" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"whatsapp" text DEFAULT '' NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" "catalog_status" DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "staff_users_role_check" CHECK ("staff_users"."role" in ('admin', 'vendedor', 'operador', 'financeiro'))
);
--> statement-breakpoint
ALTER TABLE "equipment_prices" ADD CONSTRAINT "equipment_prices_equipment_id_equipments_id_fk" FOREIGN KEY ("equipment_id") REFERENCES "public"."equipments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "equipments" ADD CONSTRAINT "equipments_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_contract_items" ADD CONSTRAINT "rental_contract_items_contract_id_rental_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."rental_contracts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rental_contract_items" ADD CONSTRAINT "rental_contract_items_equipment_id_equipments_id_fk" FOREIGN KEY ("equipment_id") REFERENCES "public"."equipments"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_contracts" ADD CONSTRAINT "rental_contracts_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_contracts" ADD CONSTRAINT "rental_contracts_seller_id_staff_users_id_fk" FOREIGN KEY ("seller_id") REFERENCES "public"."staff_users"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_quote_items" ADD CONSTRAINT "rental_quote_items_quote_id_rental_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."rental_quotes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rental_quote_items" ADD CONSTRAINT "rental_quote_items_equipment_id_equipments_id_fk" FOREIGN KEY ("equipment_id") REFERENCES "public"."equipments"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_quotes" ADD CONSTRAINT "rental_quotes_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "rental_quotes" ADD CONSTRAINT "rental_quotes_seller_id_staff_users_id_fk" FOREIGN KEY ("seller_id") REFERENCES "public"."staff_users"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "categories_slug_key" ON "categories" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "categories_category_code_idx" ON "categories" USING btree ("category_code");--> statement-breakpoint
CREATE INDEX "categories_status_idx" ON "categories" USING btree ("status");--> statement-breakpoint
CREATE INDEX "customers_status_idx" ON "customers" USING btree ("status");--> statement-breakpoint
CREATE INDEX "customers_nome_idx" ON "customers" USING btree ("nome");--> statement-breakpoint
CREATE INDEX "customers_document_idx" ON "customers" USING btree ("document");--> statement-breakpoint
CREATE UNIQUE INDEX "products_slug_key" ON "equipments" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "equipments_category_id_idx" ON "equipments" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "equipments_status_idx" ON "equipments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "equipments_equipment_code_idx" ON "equipments" USING btree ("equipment_code");--> statement-breakpoint
CREATE INDEX "rental_contract_items_contract_id_idx" ON "rental_contract_items" USING btree ("contract_id");--> statement-breakpoint
CREATE INDEX "rental_contract_items_equipment_id_idx" ON "rental_contract_items" USING btree ("equipment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "rental_contracts_contract_number_key" ON "rental_contracts" USING btree ("contract_number");--> statement-breakpoint
CREATE INDEX "rental_contracts_customer_id_idx" ON "rental_contracts" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "rental_contracts_seller_id_idx" ON "rental_contracts" USING btree ("seller_id");--> statement-breakpoint
CREATE INDEX "rental_contracts_status_idx" ON "rental_contracts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "rental_contracts_start_date_idx" ON "rental_contracts" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "rental_quote_items_quote_id_idx" ON "rental_quote_items" USING btree ("quote_id");--> statement-breakpoint
CREATE UNIQUE INDEX "rental_quotes_quote_number_key" ON "rental_quotes" USING btree ("quote_number");--> statement-breakpoint
CREATE INDEX "rental_quotes_quote_number_idx" ON "rental_quotes" USING btree ("quote_number");--> statement-breakpoint
CREATE INDEX "rental_quotes_customer_id_idx" ON "rental_quotes" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "rental_quotes_seller_id_idx" ON "rental_quotes" USING btree ("seller_id");--> statement-breakpoint
CREATE INDEX "rental_quotes_status_idx" ON "rental_quotes" USING btree ("status");--> statement-breakpoint
CREATE INDEX "staff_users_status_idx" ON "staff_users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "staff_users_nome_idx" ON "staff_users" USING btree ("nome");--> statement-breakpoint
CREATE INDEX "staff_users_role_idx" ON "staff_users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "staff_users_auth_user_id_idx" ON "staff_users" USING btree ("auth_user_id");